### ISSUE TITLE
Missing Codec for Array[java.lang.Byte]

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#15]
Workaround:

```scala
import java.lang.{Byte ⇒ JByte}

implicit val javaByteArrayEnc: Encoder[Array[JByte]] = Encoder.forByteArray.compose(javaArray ⇒ javaArray.map(x ⇒ x: Byte))
implicit val javaByteArrayDec: Decoder[Array[JByte]] = Decoder.forByteArray.map(scalaArray ⇒ scalaArray.map(x ⇒ x: JByte))

```

**Comment by abrighton** [comment]
I noticed an array of Bytes encoded in Scala can be read in Scala and Python, but the same thing encoded from Python results in this error in Scala: 
```
io.bullet.borer.Borer$Error$InvalidInputData: Expected Bytes but got Array Header (3) (input position 187)
	at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:442)
	at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:438)
	at io.bullet.borer.InputReader.readBytes(Reader.scala:211)
	at io.bullet.borer.InputReader.readByteArray(Reader.scala:204)
	at io.bullet.borer.Decoder$.$anonfun$forByteArray$1(Decoder.scala:69)
	at io.bullet.borer.Decoder$DecoderOps$.$anonfun$map$1(Decoder.scala:54)
	at csw.params.core.formats.CborSupport$.$anonfun$paramDecExistential$1(CborSupport.scala:77)
	at io.bullet.borer.InputReader.read(Reader.scala:352)
	at io.bullet.borer.InputReader.apply(Reader.scala:63)
	at io.bullet.borer.Decoder$.rec$1(Decoder.scala:195)
	at io.bullet.borer.Decoder$.$anonfun$forIterable$1(Decoder.scala:201)
	at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.fillArgsAndConstruct$1(MapBasedCodecs.scala:207)
	at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.$anonfun$combine$2(MapBasedCodecs.scala:219)
	at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.readTypeIdAndValue$1(MapBasedCodecs.scala:233)
	at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.$anonfun$dispatch$2(MapBasedCodecs.scala:241)
	at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:160)
	at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:98)
	at csw.event.client.internal.redis.EventRomaineCodecs$EventRomaineCborCodec$.fromBytes(EventRomaineCodecs.scala:56)
```

**Comment by sirthias** [comment]
It looks like in your case the Python encoder doesn't encode the bytes as a CBOR "ByteString" but rather as an actual CBOR array of single-byte values, which is quite a bit less efficient.

What BORER can do here is to simply also accept the less efficient variant when decoding, as this would increase seamless interoperability.

**Comment by abrighton** [comment]
I was able to fix the problem by encoding the values in python byte strings. 
Thanks.

**Comment by mushtaq** [comment]
@sirthias, the original issue was different than what Allan reported. 

I hope you closed it because providing codec for Array[java.lang.Byte] as in the title is not a good idea?

**Comment by sirthias** [comment]
@mushtaq Yes, the original issue was different.
However, the 0.9.0 release does provide a pre-defined codec for `Array[T]` [here](https://github.com/sirthias/borer/blob/208ebd77a387987fc92a1c5dab6585a05bb77f5f/core/src/main/scala/io/bullet/borer/Encoder.scala#L223) and [here](https://github.com/sirthias/borer/blob/208ebd77a387987fc92a1c5dab6585a05bb77f5f/core/src/main/scala/io/bullet/borer/Decoder.scala#L234), so the original issue should be taken care of as well, in the sense of having _some_ codec available for `Array[java.lang.Byte]`.

However, this codec does not encode to / decode from a CBOR "ByteString".
In order for that to work you'd have to manually unbox/box in the way you show it here in the original ticket description. The reason for this is the same as brought up in the discussion around https://github.com/sirthias/borer/issues/14.
