### ISSUE TITLE
Array[Int] decoding does not work

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#2]
I tried this:
```scala
implicit val intArrEnc: Encoder[Array[Int]] = Encoder.forArray[Integer].compose[Array[Int]](_.map(x => x: Integer))
implicit val intArrDec: Decoder[Array[Int]] = Decoder.forArray[Integer].map[Array[Int]](_.map(x => x: Int))
val intArr = Array(1, 2, 3, 4)
val bytes: Array[Byte] = Cbor.encode(intArr).toByteArray
val blob: Array[Int] = Cbor.decode(bytes).to[Array[Int]].value
```
I get this error:
```error
Exception in thread "main" io.bullet.borer.Borer$Error$General: java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.Integer; ([Ljava.lang.Object; and [Ljava.lang.Integer; are in module java.base of loader 'bootstrap')
	at io.bullet.borer.Borer$DecodingSetup.to(Borer.scala:265)
	at spikes.Demo$.main(Blob.scala:60)
	at spikes.Demo.main(Blob.scala)
Caused by: java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.Integer; ([Ljava.lang.Object; and [Ljava.lang.Integer; are in module java.base of loader 'bootstrap')
	at io.bullet.borer.Decoder$DecoderOps$.$anonfun$map$1(Decoder.scala:40)
	at io.bullet.borer.Decoder$.$anonfun$apply$1(Decoder.scala:32)
	at io.bullet.borer.Borer$DecodingSetup.to(Borer.scala:260)
	... 2 more
```

**Comment by sirthias** [comment]
Thank you, @mushtaq!
I'll release a new version containing a fix today or tomorrow...

**Comment by mushtaq** [comment]
@sirthias, thanks for a quick response. I wonder why does borer does not provide codecs for Array[primitives] out of the box? I feel many projects will end up writing those on their own.

**Comment by sirthias** [comment]
@mushtaq, yes, that's a very valid point.
I just added a respective commit to the `md/0.8` branch, which will get merged and released very soon.
Thanks again!

**Comment by mushtaq** [comment]
@sirthias thank you so much! Looking forward to 0.8.

**Comment by sirthias** [comment]
Ok, just released 0.8 to sonatype.
Should appear on maven central in a few hours...

**Comment by plokhotnyuk** [comment]
Mathias, sorry for offtopic, but will that release have a JSON support?

If yes, then I think you would be interested on feedback about current JSON support in the md/0.8 branch...

**Comment by mushtaq** [comment]
@sirthias Thanks. Upgraded, and working as expected.
