### ISSUE TITLE
[0.9.0] def apply() in the companion breaks decoding 

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#23]
This is while upgrading to 0.9.0

**Test**

```scala
case class Box(id: String)
object Box {
  def apply(): Box = new Box("default")
}

implicit val boxCodec: Codec[Box] = Codec.forCaseClass[Box]
val array                         = Cbor.encode(Box("abc")).toByteArray
Cbor.decode(array).to[Box].value
```

**Error**

```txt
io.bullet.borer.Borer$Error$InvalidInputData: Expected Array Header (0) but got Text (input position 0)
[info]   at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:442)
[info]   at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:438)
[info]   at io.bullet.borer.InputReader.readArrayHeader(Reader.scala:295)
[info]   at io.bullet.borer.InputReader.readArrayHeader(Reader.scala:292)
[info]   at io.bullet.borer.DecoderFromApply.$anonfun$from$1(DecoderFromApply.scala:15)
[info]   at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:160)
[info]   at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:98)
```

**Comment by sirthias** [comment]
Thank you once gain, @mushtaq, for reporting!
A work-around for 0.9.0 would be:

```scala
implicit val boxCodec: Codec[Box] = Codec(
  Encoder.forCaseClass[Box],
  Decoder.from(Box(_: String))
)
```
