### ISSUE TITLE
Problem with Encoding BigDecimals

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [sirthias/borer#269]
Hello @sirthias ,

Thanks for writing this library and the easy integrations with `circe` and `akka`, which plays well into our tech stack at work.

I tried to switch our circe JSON payload with `CBOR` and noticed a problem with encoding `BigDecimal`. 

I was able to reproduce the problem on a smaller scale

```scala
import io.bullet.borer.compat.circe._

 case class Foo(x: BigDecimal)

 val bigDecimal = Foo(BigDecimal(23.00))

 implicit val fooEncoder = deriveEncoder[Foo]

 def borerToEntityMarshallerCbor[T : BorerEncoder]: ToEntityMarshaller[T] =
      compat.akkaHttp.borerMarshaller(prefer = io.bullet.borer.Cbor)

Marshal(bigDecimal).to[RequestEntity](borerToEntityMarshallerCbor[Foo], system.dispatcher)

```
Error Message: I get a stackoverflow error
```bash
SampleClientTest *** ABORTED *** (1 second, 274 milliseconds)
  java.lang.StackOverflowError:
  at java.math.BigDecimal.<init>(BigDecimal.java:383)
  at java.math.BigDecimal.<init>(BigDecimal.java:806)
  at scala.math.BigDecimal$.exact(BigDecimal.scala:126)
  at scala.math.BigDecimal$.apply(BigDecimal.scala:284)
  at io.circe.BiggerDecimalJsonNumber.$anonfun$toBigDecimal$1(JsonNumber.scala:98)
  at scala.Option.map(Option.scala:230)
  at io.circe.BiggerDecimalJsonNumber.toBigDecimal(JsonNumber.scala:95)
  at io.bullet.borer.compat.circe$$anon$1.onNumber(circe.scala:59)
  at io.bullet.borer.compat.circe$$anon$1.onNumber(circe.scala:42)
  at io.circe.Json$JNumber.foldWith(Json.scala:328)
```

I'm not sure if I'm using the library incorrectly or if I have stumbled upon a bug that others haven't. Let me know if you would like more details

**Comment by sirthias** [comment]
Thank you, @ArulselvanMadhavan, for reporting this bug!
I'll quickly release 1.6.1 with the fix for you...

**Comment by sirthias** [comment]
And done.
Release 1.6.1 is on sonatype and should appear on maven central shortly.
Thanks again for reporting!

**Comment by ArulselvanMadhavan** [comment]
Thanks @sirthias
