### ISSUE TITLE
NPE (or SOE) during parsing or serialization of recursive structures

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#28]
Parsing:
```
> console
[info] Starting scala interpreter...
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import io.bullet.borer._
import io.bullet.borer.derivation.MapBasedCodecs._

case class Nested(n: Option[Nested] = None)

object Nested {
  implicit val Codec(encoder: Encoder[Nested], decoder: Decoder[Nested]) = deriveCodec[Nested]
}

val obj = io.bullet.borer.Json.decode("""{"n":{"n":{"n":{}}}}""".getBytes).to[Nested].value
println(obj)

// Exiting paste mode, now interpreting.

io.bullet.borer.Borer$Error$General: java.lang.NullPointerException (input position 1)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:101)
  ... 44 elided
Caused by: java.lang.NullPointerException
  at io.bullet.borer.InputReader.read(Reader.scala:352)
  at io.bullet.borer.Decoder$$anon$1.$anonfun$withDefaultValue$1(Decoder.scala:188)
  at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.fillArgsAndConstruct$1(MapBasedCodecs.scala:207)
  at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.$anonfun$combine$2(MapBasedCodecs.scala:215)
  at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:160)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:98)
  ... 44 more
```
Serialization:
```
> console
[info] Starting scala interpreter...
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import io.bullet.borer._
import io.bullet.borer.derivation.MapBasedCodecs._

case class Nested(n: Option[Nested] = None)

object Nested {
  implicit val Codec(encoder: Encoder[Nested], decoder: Decoder[Nested]) = deriveCodec[Nested]
}

val bytes = io.bullet.borer.Json.encode(Nested(Some(Nested(None)))).toByteArray
println(new String(bytes))

// Exiting paste mode, now interpreting.

io.bullet.borer.Borer$Error$General: java.lang.NullPointerException (Output.ToByteArray index 4)
  at io.bullet.borer.EncodingSetup$Impl.bytes(EncodingSetup.scala:131)
  at io.bullet.borer.EncodingSetup$Impl.toByteArray(EncodingSetup.scala:112)
  ... 36 elided
Caused by: java.lang.NullPointerException
  at io.bullet.borer.Writer.write(Writer.scala:86)
  at io.bullet.borer.Encoder$$anon$1$$anon$2.write(Encoder.scala:177)
  at io.bullet.borer.Encoder$$anon$1$$anon$2.write(Encoder.scala:173)
  at io.bullet.borer.derivation.MapBasedCodecs$deriveEncoder$.rec$1(MapBasedCodecs.scala:55)
  at io.bullet.borer.derivation.MapBasedCodecs$deriveEncoder$.$anonfun$combine$1(MapBasedCodecs.scala:77)
  at io.bullet.borer.Writer.write(Writer.scala:86)
  at io.bullet.borer.EncodingSetup$Impl.render(EncodingSetup.scala:180)
  at io.bullet.borer.EncodingSetup$Impl.bytes(EncodingSetup.scala:128)
  ... 37 more
```

The same code when enclosed in curly brackets defers derivation until first call to decoder/encoder and produces SOE:
```
> console
[info] Starting scala interpreter...
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

{
import io.bullet.borer._
import io.bullet.borer.derivation.MapBasedCodecs._

case class Nested(n: Option[Nested] = None)

object Nested {
  implicit val Codec(encoder: Encoder[Nested], decoder: Decoder[Nested]) = deriveCodec[Nested]
}

val obj = io.bullet.borer.Json.decode("""{"n":{"n":{"n":{}}}}""".getBytes).to[Nested].value
println(obj)
}


// Exiting paste mode, now interpreting.

java.lang.StackOverflowError
  at Nested$2$.nestedTypeclass$macro$1$lzycompute$1(<pastie>:19)
  at Nested$2$.nestedTypeclass$macro$1$1(<pastie>:19)
  ... 1022 elided
```

**Comment by sirthias** [comment]
Thank you once more for reporting, Andriy!
