### ISSUE TITLE
Unexpected exception when parsing a `null` value for an optional field

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#29]
```
[info] Starting scala interpreter...
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> case class A(b: Option[Int] = None, c: Option[String] = None)
defined class A

scala> import io.bullet.borer._
<console>:11: warning: Unused import
       import io.bullet.borer._
                              ^
import io.bullet.borer._

scala> import io.bullet.borer.derivation.MapBasedCodecs._
<console>:10: warning: Unused import
       import io.bullet.borer._
                              ^
<console>:14: warning: Unused import
       import io.bullet.borer.derivation.MapBasedCodecs._
                                                        ^
import io.bullet.borer.derivation.MapBasedCodecs._

scala> implicit val c = deriveCodec[A]
<console>:12: warning: Unused import
       import io.bullet.borer._
                              ^
c: io.bullet.borer.Codec[A] = Codec(io.bullet.borer.derivation.MapBasedCodecs$deriveEncoder$$$Lambda$5709/1448885594@76b91f1a,io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$$$Lambda$5732/1761122012@1da255b7)

scala> Json.decode("""{}""".getBytes).to[A].value
<console>:15: warning: Unused import
       import io.bullet.borer.derivation.MapBasedCodecs._
                                                        ^
res0: A = A(None,None)

scala> Json.decode("""{"b":1}""".getBytes).to[A].value
<console>:15: warning: Unused import
       import io.bullet.borer.derivation.MapBasedCodecs._
                                                        ^
res1: A = A(Some(1),None)

scala> Json.decode("""{"c":"x"}""".getBytes).to[A].value
<console>:15: warning: Unused import
       import io.bullet.borer.derivation.MapBasedCodecs._
                                                        ^
res2: A = A(None,Some(x))

scala> Json.decode("""{"b":1,"c":"x"}""".getBytes).to[A].value
<console>:15: warning: Unused import
       import io.bullet.borer.derivation.MapBasedCodecs._
                                                        ^
res3: A = A(Some(1),Some(x))

scala> Json.decode("""{"b":1,"c":null}""".getBytes).to[A].value
<console>:15: warning: Unused import
       import io.bullet.borer.derivation.MapBasedCodecs._
                                                        ^
<console>:10: warning: Unused import
       import io.bullet.borer._
                              ^
<console>:13: warning: Unused import
       import io.bullet.borer.derivation.MapBasedCodecs._
                                                        ^
<console>:15: warning: Unused import
       import c
                                                   ^
io.bullet.borer.Borer$Error$InvalidInputData: Expected String or Text Bytes but got Null (input position 7)
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:442)
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:438)
  at io.bullet.borer.InputReader.readString(Reader.scala:239)
  at io.bullet.borer.Decoder$.$anonfun$forString$1(Decoder.scala:68)
  at io.bullet.borer.InputReader.read(Reader.scala:352)
  at io.bullet.borer.Decoder$$anon$1.$anonfun$withDefaultValue$1(Decoder.scala:188)
  at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.fillArgsAndConstruct$1(MapBasedCodecs.scala:207)
  at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.$anonfun$combine$2(MapBasedCodecs.scala:215)
  at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:160)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:98)
  ... 36 elided
```

**Comment by sirthias** [comment]
Borer has no special handling of `null` values anywhere. They are values like every other one and thus need to match the types of your model. In your case you have an `Option[String] = None`, which means that the member is either present (`Some`) or not present (`None`).
Nowhere in your types you are stating that `null` is a legal value.

The way to solve the problem here is to

- use the type `Nullable[String]` to have `null` be decoded as the empty string

- use the type `Nullable[Option[String]]` if you want to encode `None` as `null` and `Some` simply as the non-null `String`

- use the type `Option[Nullable[String]] = None` if you want to encode `None` as "not present" and `Some` as "present", with a `null` value being interpreted as `Some("")`

the type `Option[Nullable[String]]`

**Comment by plokhotnyuk** [comment]
Does it have any option to alter the default parsing of `Option[String]` without using of `Nullable`?
