### ISSUE TITLE
Cannot parse whole numbers as Double or Float in JSON

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#3]
```
scala> io.bullet.borer.Json.decode("1".getBytes).to[Double].value
io.bullet.borer.Borer$Error$UnexpectedDataItem: Unexpected data item: Expected [Double] but got [Int]
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:373)
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:369)
  at io.bullet.borer.InputReader.readDouble(Reader.scala:150)
  at io.bullet.borer.Decoder$.$anonfun$forDouble$1(Decoder.scala:56)
  at io.bullet.borer.Decoder$.$anonfun$forDouble$1$adapted(Decoder.scala:56)
  at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:177)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:109)
  ... 36 elided

scala> io.bullet.borer.Json.decode("1".getBytes).to[Float].value
io.bullet.borer.Borer$Error$UnexpectedDataItem: Unexpected data item: Expected [Float] but got [Int]
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:373)
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:369)
  at io.bullet.borer.InputReader.readFloat(Reader.scala:139)
  at io.bullet.borer.Decoder$.$anonfun$forFloat$1(Decoder.scala:55)
  at io.bullet.borer.Decoder$.$anonfun$forFloat$1$adapted(Decoder.scala:55)
  at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:177)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:109)
  ... 36 elided
```

**Comment by sirthias** [comment]
Thank you for reporting, @plokhotnyuk!
My initial reaction was to mark this as a "won't fix", since for conversions between the different numeric types should always be explicit. (All my projects always have the "-Ywarn-numeric-widen" and "-Xfatal-warnings" compiler options enabled).

However, seeing that scalac also has numeric widening of integers to floating point values be enabled by default and _BORER_ also implicitly converts between the different numeric integer types (Bytes, Shorts, Ints and Longs) I'll add a `autoConvertLongToFloat` config value, that will even be enabled by default.
