### ISSUE TITLE
Some float numbers cannot be parsed from JSON as Float with a strange error message

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#5]
```
scala> "1.1999999".toFloat
res0: Float = 1.1999999

scala> io.bullet.borer.Json.decode("1.1999999".getBytes).to[Float].value
io.bullet.borer.Borer$Error$UnexpectedDataItem: Unexpected data item: Expected [Float] but got [Double]
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:373)
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:369)
  at io.bullet.borer.InputReader.readFloat(Reader.scala:139)
  at io.bullet.borer.Decoder$.$anonfun$forFloat$1(Decoder.scala:55)
  at io.bullet.borer.Decoder$.$anonfun$forFloat$1$adapted(Decoder.scala:55)
  at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:177)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:109)
  ... 36 elided
```

**Comment by sirthias** [comment]
Thank you for reporting!

**Comment by abrighton** [comment]
This might be related: I get the same exception when a python app encodes floating point values that are decoded in Scala. Python doesn't make a difference between float and double and the Scala code wants a Float in this case. Would it be possible to allow a Double where a Float is expected? That already works for integer values. Long, Short and Int don't seem to cause the same problems between Python and Scala, event though they are all the same for Python.

**Comment by sirthias** [comment]
@abrighton Are you still seeing this error with the latest borer 0.9.0?

**Comment by abrighton** [comment]
We were using 0.8.0. I'll try the newer version and let you know.

**Comment by abrighton** [comment]
So I tested the code with borer-0.9.0 and get the same error when python encodes a floating point value and the Scala decoder is expecting a Float:

```
io.bullet.borer.Borer$Error$InvalidInputData: Expected Float but got Double (input position 335)
	at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:442)
	at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:438)
	at io.bullet.borer.InputReader.readFloat(Reader.scala:166)
	at io.bullet.borer.Decoder$.$anonfun$forFloat$1(Decoder.scala:66)
	at io.bullet.borer.Decoder$.$anonfun$forFloat$1$adapted(Decoder.scala:66)
	at io.bullet.borer.InputReader.read(Reader.scala:352)
	at io.bullet.borer.Decoder$.rec$2(Decoder.scala:219)
	at io.bullet.borer.Decoder$.$anonfun$forArray$1(Decoder.scala:223)
	at io.bullet.borer.Decoder$DecoderOps$.$anonfun$map$1(Decoder.scala:54)
	at io.bullet.borer.Decoder$DecoderOps$.$anonfun$map$1(Decoder.scala:54)
	at io.bullet.borer.InputReader.read(Reader.scala:352)
	at io.bullet.borer.Decoder$.rec$2(Decoder.scala:219)
	at io.bullet.borer.Decoder$.$anonfun$forArray$1(Decoder.scala:223)
	at io.bullet.borer.Decoder$DecoderOps$.$anonfun$map$1(Decoder.scala:54)
	at csw.params.core.formats.CborSupport$.$anonfun$paramDecExistential$1(CborSupport.scala:77)
	at io.bullet.borer.InputReader.read(Reader.scala:352)
	at io.bullet.borer.InputReader.apply(Reader.scala:63)
	at io.bullet.borer.Decoder$.rec$1(Decoder.scala:195)
	at io.bullet.borer.Decoder$.$anonfun$forIterable$1(Decoder.scala:201)
	at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.fillArgsAndConstruct$1(MapBasedCodecs.scala:207)
	at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.$anonfun$combine$2(MapBasedCodecs.scala:219)
	at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.readTypeIdAndValue$1(MapBasedCodecs.scala:233)
	at io.bullet.borer.derivation.MapBasedCodecs$deriveDecoder$.$anonfun$dispatch$2(MapBasedCodecs.scala:241)
	at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:160)
	at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:98)
	at csw.event.client.internal.redis.EventRomaineCodecs$EventRomaineCborCodec$.fromBytes(EventRomaineCodecs.scala:55)

```

**Comment by sirthias** [comment]
Ok, I see.
borer 0.9.0 has a config flag that will help you: `readDoubleAlsoAsFloat`.
Here is how you use it:

```scala
Json.decode(bytes).withConfig(Json.DecodingConfig(readDoubleAlsoAsFloat = true)).toByteArray
```

With this config setting the error should go away.

**Comment by abrighton** [comment]
Yes, that fixed it. Thanks!
