### ISSUE TITLE
Cannot parse nested ADT

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#55]
Code to reproduce:
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

import io.bullet.borer._
import io.bullet.borer.derivation.MapBasedCodecs._

sealed trait Geometry extends Product with Serializable
case class Point(coordinates: (Double, Double)) extends Geometry
case class MultiPoint(coordinates: IndexedSeq[(Double, Double)] = Vector.empty) extends Geometry
case class LineString(coordinates: IndexedSeq[(Double, Double)] = Vector.empty) extends Geometry
case class MultiLineString(coordinates: IndexedSeq[IndexedSeq[(Double, Double)]] = Vector.empty) extends Geometry
case class Polygon(coordinates: IndexedSeq[IndexedSeq[(Double, Double)]] = Vector.empty) extends Geometry
case class MultiPolygon(coordinates: IndexedSeq[IndexedSeq[IndexedSeq[(Double, Double)]]] = Vector.empty) extends Geometry
case class GeometryCollection(geometries: IndexedSeq[Geometry] = Vector.empty) extends Geometry

sealed trait GeoJSON extends Product with Serializable
case class Feature(properties: Map[String, String] = Map.empty, geometry: Geometry, bbox: Option[(Double, Double, Double, Double)] = None) extends GeoJSON
case class FeatureCollection(features: IndexedSeq[GeoJSON] = Vector.empty, bbox: Option[(Double, Double, Double, Double)] = None) extends GeoJSON

implicit val flatAdtEncoding: AdtEncodingStrategy = AdtEncodingStrategy.flat(typeMemberName = "type")

implicit val Codec(geoJsonEnc: Encoder[GeoJSON], geoJsonDec: Decoder[GeoJSON]) = {
  implicit lazy val c1: Codec[Geometry] = {
    implicit val c11: Codec[Point] = deriveCodec
    implicit val c12: Codec[MultiPoint] = deriveCodec
    implicit val c13: Codec[LineString] = deriveCodec
    implicit val c14: Codec[MultiLineString] = deriveCodec
    implicit val c15: Codec[Polygon] = deriveCodec
    implicit val c16: Codec[MultiPolygon] = deriveCodec
    implicit val c17: Codec[GeometryCollection] = deriveCodec
    deriveCodec[Geometry]
  }
  implicit val c2: Codec[Feature] = deriveCodec
  implicit val c3: Codec[FeatureCollection] = deriveCodec
  deriveCodec[GeoJSON]
}

// Exiting paste mode, now interpreting.
...
scala> new String(io.bullet.borer.Json.encode[GeoJSON](FeatureCollection(Vector(Feature(geometry = Polygon(Vector(Vector((7.697223,47.543327)))))))).toByteArray)
...
res0: String = {"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[7.697223,47.543327]]]}}]}

scala> io.bullet.borer.Json.decode(res0.getBytes).to[GeoJSON].value
...
io.bullet.borer.Borer$Error$InvalidInputData: Expected Map for decoding an instance of type `GeoJSON` but got Start of unbounded Map (input position 41)
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:617)
  at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:613)
  at io.bullet.borer.AdtEncodingStrategy$$anon$1.failNoMap$1(AdtEncodingStrategy.scala:175)
  at io.bullet.borer.AdtEncodingStrategy$$anon$1.readAdtEnvelopeOpen(AdtEncodingStrategy.scala:234)
  at .$anonfun$x$1$4(<console>:32)
  at io.bullet.borer.InputReader.read(Reader.scala:516)
  at io.bullet.borer.InputReader.rec$1(Reader.scala:520)
  at io.bullet.borer.InputReader.readUntilBreak(Reader.scala:521)
  at io.bullet.borer.Decoder$.$anonfun$forIterable$1(Decoder.scala:255)
  at io.bullet.borer.InputReader.read(Reader.scala:516)
  at FeatureCollectionDecoder$1.readObject$9(<console>:31)
  at FeatureCollectionDecoder$1.read(<console>:31)
  at $anon$18.read(<console>:31)
  at $anon$18.read(<console>:31)
  at io.bullet.borer.InputReader.read(Reader.scala:516)
  at .$anonfun$x$1$4(<console>:32)
  at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:169)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:100)
  ... 36 elided
```

**Comment by plokhotnyuk** [comment]
@sirthias Thanks! 

Will you cut a release for a couple of fixes that you pushed into the master?

**Comment by sirthias** [comment]
Thank YOU, @plokhotnyuk, for reporting this problem!
This was an important fix!

And yes, I am in the process of applying one more thing and then releasing borer 1.0.0.

**Comment by plokhotnyuk** [comment]
@sirthias could you, please, look into [this error](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/TwitterAPIReading.scala#L28)? is it worth to be reported and fixed before cutting of borer 1.0.0?

**Comment by sirthias** [comment]
ok, will do, thx

**Comment by sirthias** [comment]
It looks like the field `in_reply_to_status_id` is defined as `Option[String] = None` but in the JSON source it's `null`. So _borer_ says that it expects a `String` rather than `null`.

Can you try this import and see whether the problem disappears?:

```scala
import io.bullet.borer.NullOptions._
```

**Comment by plokhotnyuk** [comment]
@sirthias thanks, it helped and the problem is solved now: https://github.com/plokhotnyuk/jsoniter-scala/commit/885ff8e9acae78757a1b3b6d0c3f67d32e14198d
