### ISSUE TITLE
Extra input fields cause error while decoding to empty case classes and case objects of an ADT

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#600]
Problem occurs with both `Json` and `Cbor`, and also when `AdtEncodingStrategy.flat()` is enabled.
Borer version: 1.10.1

```scala
sealed trait Base

case class A(x: Int) extends Base
case class B()       extends Base
case object C        extends Base

implicit lazy val baseCodecs: Decoder[Base] = MapBasedCodecs.deriveAllDecoders

val jsonA =
  """
    |{"A":{"x":100, "extra": "should be ignored"}}
    |""".stripMargin

val jsonB =
  """
    |{"B":{"extra": "should be ignored"}}
    |""".stripMargin

val jsonC =
  """
    |{"C":{"extra": "should be ignored"}}
    |""".stripMargin


println(Json.decode(jsonA.getBytes).to[Base].value) // A(100)
println(Json.decode(jsonB.getBytes).to[Base].value) // error as below
println(Json.decode(jsonC.getBytes).to[Base].value) // error as below
```

```txt
io.bullet.borer.Borer$Error$InvalidInputData: Expected BREAK but got Chars (input position 6)
[info]   at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:593)
[info]   at io.bullet.borer.InputReader.unexpectedDataItem(Reader.scala:590)
[info]   at io.bullet.borer.InputReader.readBreak(Reader.scala:475)
[info]   at io.bullet.borer.InputReader.readMapClose(Reader.scala:577)
```

**Comment by sirthias** [comment]
Ok, thank you, @mushtaq !
I'll look into it as soon as I get a chance...

**Comment by mushtaq** [comment]
@sirthias If I want to give a try at fixing this, can you help me point out where to look in the code?

**Comment by sirthias** [comment]
Just had some time this afternoon to quickly get this sorted.
It was a rather easy fix...

**Comment by sirthias** [comment]
Thank you again, @mushtaq, for reporting this!
Your test case made this very easy to reproduce and fix!

**Comment by mushtaq** [comment]
Oh nice! Thank you so much. 

I had created a very bad workaround which I will get rid of now 😄
