### ISSUE TITLE
StackOverflowError when compiling with Scala 3

### ISSUE THREAD

**Issue by OndrejSpanel** [sirthias/borer#608]
When porting my project to Scala 3, I experience StackOverflowError in encoder derivation. It does not seem to be real infinite recursion, because when I change -Xss options for SBT to use 2M of stack space, the compilation succeeds.

Still it seems the encoder derivation uses an unusual amount of stack space with Scala 3 - I never experienced issues like this when working with Scala 2. The issue is a bit random, as default stack size is platform dependent on JVM, therefore to me it shown only on GitHub runners (Linux, Temurin Java 11) and not on my computer (Windows, Oracle JDK 11).

I have originally reported this as https://github.com/lampepfl/dotty/issues/16548. I am not sure if this is more Borer or Scala 3 issue (of if it is an issue at all). I have created a small repro projects, which uses -Xss500k setting to make sure it is reproduced reliably. 

With the repro project the functions `PCPCheckAndHeal.transform` / `TreeMapWithImplicits.transform` seem to be recursed over 100 times, which seems unexpectedly high number to me, given the repro has about 60 lines.

The project reproducing the issue can be found at https://github.com/OndrejSpanel/borerScala3Error

When running on Windows, I use following steps to reproduce:

With CMD:

```
set SBT_OPTS=-Xss500k
sbt clean compile
```

With Powershell:

```
$Env:SBT_OPTS="-Xss500k"
sbt clean compile
```

The options are already configured in the GitHub workflow.

The error callstack with this setting can be see in https://github.com/OndrejSpanel/borerScala3Error/actions/runs/3738568151/jobs/6344782225, I extract top and bottom from it here:

Callstack excerpt:
```text
[error] java.lang.StackOverflowError
[error] 	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:73)
[error] 	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:79)
[error] 	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:149)

[error] 	at dotty.tools.dotc.transform.Staging$$anon$2.transform(Staging.scala:73)
[error] 	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:18)
[error] 	at dotty.tools.dotc.transform.Staging.run(Staging.scala:69)
```

<details>
<summary>Full callstack</summary>

    java.lang.StackOverflowError
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:73)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:79)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:149)
	at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:61)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1225)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1225)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock(tpd.scala:1230)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1426)
	at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:49)
	at dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:79)
	at dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:132)
	at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:61)
	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1446)
        ...
	at dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:61)
	at dotty.tools.dotc.transform.Staging$$anon$2.transform(Staging.scala:73)
	at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:18)
	at dotty.tools.dotc.transform.Staging.run(Staging.scala:69)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:316)
	at scala.collection.immutable.List.map(List.scala:246)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:320)
	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:233)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:244)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:252)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:261)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:261)
	at dotty.tools.dotc.Run.compileSources(Run.scala:185)
	at dotty.tools.dotc.Run.compile(Run.scala:169)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:35)
	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2363)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2313)
	at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
	at sbt.internal.io.Retry$.apply(Retry.scala:46)
	at sbt.internal.io.Retry$.apply(Retry.scala:28)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2311)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
        (Compile / compileIncremental) java.lang.StackOverflowError
        Total time: 9 s, completed Dec 20, 2022, 7:59:36 AM

</details>

**Comment by sirthias** [comment]
Thank you, @OndrejSpanel, for the report!
This problem isn't a Scala issue, I know what's causing this.

The difference between the Scala 2 and 3 derivation macros is huge, the new ones are a completely different implementation. In order to not having to construct trees manually the macros currently rely on on-stack recursion that's linear to the number of fields in a case class. This wasn't the case with Scala 2 since we had access to all powerful (but potentially unhygienic) quotes.
So far I don't know, how to generate a variable number of fields, etc. with the Scala 3 macros without manual tree construction and within bounded stack space and I'm not sure wether it's even possible.

So, I'd suggest we keep this ticket open until a proper solution is found.
The good thing is that for any project there will always be a stack size that will make _borer_ derivation compile. The bad thing is that this size has to be found by trial and error and might have to increase as project model classes become larger (i.e. grow in their max number of fields).

**Comment by sirthias** [comment]
Just now got a chance to look at your reproduction repo.
Thank you @OndrejSpanel for providing it!
The error stack trace really looks unusually large for such relatively simple model classes....

Seeing this I assume we'll hit this SOE problem ourselves pretty quickly in the very near future during the upgrade of our own projects to Scala 3 and therefore the latest _borer_ versions.
It might well be that there is something we can do on the borer side to somewhat "compress" the amount of stack space required for each recursion.

Or move away from recursions completely by biting the bullet and dropping down to manual tree manipulation at very few, key locations.

I'll use this ticket to post the progress...

**Comment by sirthias** [comment]
Ok, I just pushed a commit that partially unrolls the recursion loops that the derivation macros are currently based on.
This should greatly reduce the stack pressure by up to a factor of 8 for larger classes.
The fix is part of the freshly released borer version 1.10.2 that just made it to sonatype.
Let me know if this fixes your issue, @OndrejSpanel !

**Comment by OndrejSpanel** [comment]
Both the artificial repro (see https://github.com/OndrejSpanel/borerScala3Error/actions) and my real project now compile fine with the small stack sizes which exhibited the exception before.

Thanks for fixing this.

**Comment by sirthias** [comment]
Ok, great.
Then I'll close this ticket for now...
