### ISSUE TITLE
Cannot parse a number as Array[Long] or Array[BigInt] or Array[BigDecimal] from a JSON array

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#7]
```
scala> io.bullet.borer.Json.decode("[3326704554664441231]".getBytes).to[Array[Long]].value
io.bullet.borer.Borer$Error$InvalidJsonData: Invalid JSON syntax
  at io.bullet.borer.json.JsonParser.io$bullet$borer$json$JsonParser$$failInvalidJsonSyntax(JsonParser.scala:417)
  at io.bullet.borer.json.JsonParser.result$1(JsonParser.scala:98)
  at io.bullet.borer.json.JsonParser.parseNumberString$1(JsonParser.scala:105)
  at io.bullet.borer.json.JsonParser.breakOutToNumberString$2(JsonParser.scala:146)
  at io.bullet.borer.json.JsonParser.parseNumber$1(JsonParser.scala:164)
  at io.bullet.borer.json.JsonParser.pull(JsonParser.scala:366)
  at io.bullet.borer.InputReader.pull(Reader.scala:346)
  at io.bullet.borer.InputReader.pullIfTrue(Reader.scala:354)
  at io.bullet.borer.InputReader.tryReadArrayStart(Reader.scala:259)
  at io.bullet.borer.Decoder$.$anonfun$forArray$1(Decoder.scala:179)
  at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:177)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:109)
  ... 36 elided

scala> io.bullet.borer.Json.decode("[3326704554664441231]".getBytes).to[Array[BigInt]].value
io.bullet.borer.Borer$Error$InvalidJsonData: Invalid JSON syntax
  at io.bullet.borer.json.JsonParser.io$bullet$borer$json$JsonParser$$failInvalidJsonSyntax(JsonParser.scala:417)
  at io.bullet.borer.json.JsonParser.result$1(JsonParser.scala:98)
  at io.bullet.borer.json.JsonParser.parseNumberString$1(JsonParser.scala:105)
  at io.bullet.borer.json.JsonParser.breakOutToNumberString$2(JsonParser.scala:146)
  at io.bullet.borer.json.JsonParser.parseNumber$1(JsonParser.scala:164)
  at io.bullet.borer.json.JsonParser.pull(JsonParser.scala:366)
  at io.bullet.borer.InputReader.pull(Reader.scala:346)
  at io.bullet.borer.InputReader.pullIfTrue(Reader.scala:354)
  at io.bullet.borer.InputReader.tryReadArrayStart(Reader.scala:259)
  at io.bullet.borer.Decoder$.$anonfun$forArray$1(Decoder.scala:179)
  at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:177)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:109)
  ... 36 elided

scala> io.bullet.borer.Json.decode("[3326704554664441231]".getBytes).to[Array[BigDecimal]].value
io.bullet.borer.Borer$Error$InvalidJsonData: Invalid JSON syntax
  at io.bullet.borer.json.JsonParser.io$bullet$borer$json$JsonParser$$failInvalidJsonSyntax(JsonParser.scala:417)
  at io.bullet.borer.json.JsonParser.result$1(JsonParser.scala:98)
  at io.bullet.borer.json.JsonParser.parseNumberString$1(JsonParser.scala:105)
  at io.bullet.borer.json.JsonParser.breakOutToNumberString$2(JsonParser.scala:146)
  at io.bullet.borer.json.JsonParser.parseNumber$1(JsonParser.scala:164)
  at io.bullet.borer.json.JsonParser.pull(JsonParser.scala:366)
  at io.bullet.borer.InputReader.pull(Reader.scala:346)
  at io.bullet.borer.InputReader.pullIfTrue(Reader.scala:354)
  at io.bullet.borer.InputReader.tryReadArrayStart(Reader.scala:259)
  at io.bullet.borer.Decoder$.$anonfun$forArray$1(Decoder.scala:179)
  at io.bullet.borer.DecodingSetup$Impl.decodeFrom(DecodingSetup.scala:177)
  at io.bullet.borer.DecodingSetup$Impl.value(DecodingSetup.scala:109)
  ... 36 elided
```

**Comment by sirthias** [comment]
Thanks again for submitting this ticket!
